"""x fix

Revision ID: 237910a71ff0
Revises: 29265fd63336
Create Date: 2026-06-22 21:23:53.784466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237910a71ff0'
down_revision: Union[str, Sequence[str], None] = '29265fd63336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_data', sa.Column('x', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'profile_data', ['id'])
    op.drop_column('profile_data', 'X')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_data', sa.Column('X', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profile_data', type_='unique')
    op.drop_column('profile_data', 'x')
    # ### end Alembic commands ###
